### ISSUE TITLE
Application does not compile successfully

### ISSUE THREAD

**Issue by alimgafar** [0mkara/meteor-ng-material-baby#1]
Hi,

I was really excited to try your boilerplate. I was looking for something simple to build a demo Meteor-Angular2 application with and urigo's Socially app is just too monstrous.

I cloned it, ran the npm install and got several dependency problems. 

npm WARN angular2-meteor@0.7.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-meteor@0.7.1 requires a peer of angular2-meteor-polyfills@^0.1.1 but none was installed.
npm WARN angular2-meteor-accounts-ui@1.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-meteor-accounts-ui@1.0.0 requires a peer of @angular/common@^2.0.0 but none was installed.

When I try 'meteor run', it dies:

 meteor run --port 2100 --release 1.4.4.2 --allow-incompatible-update
[1] 70366
[[[[[ ~/Code/meteor/DevShop/meteor-ng-material-baby ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
/Users/alimgafar/.meteor/packages/coffeescript/.1.12.3_1.8it1jd++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/alimgafar/Code/meteor/DevShop/meteor-ng-material-baby/node_modules/uuid/bin'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1586:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/alimgafar/.meteor/packages/meteor-tool/.1.4.4_2.1uv44z8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:788:23)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12

I'm running Meteor 1.4.4.2

Upgrading to 1.4.4.3 gives pretty much the same error, but with new dependency issues:

meteor run --port 2100 --release 1.4.4.3 --allow-incompatible-update
[[[[[ ~/Code/meteor/DevShop/meteor-ng-material-baby ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
                                                                                   
Changes to your project's package version selections:
                                              
dynamic-import+  downgraded from 0.1.0 to 0.1.0-beta.20
meteor-base      downgraded from 1.1.0 to 1.0.4

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
/Users/alimgafar/.meteor/packages/coffeescript/.1.12.3_1.8it1jd++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/alimgafar/Code/meteor/DevShop/meteor-ng-material-baby/node_modules/thread-sleep/lib/binding'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1586:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/alimgafar/.meteor/packages/meteor-tool/.1.4.4_3.ofh9h4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:788:23)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12

--verbose doesn't add much; it only confirms that the local packages are up to date. Otherwise, no new information.

I'm giving a talk in two weeks on how to use Meteor and Angular. Angular 1 is all figured out. I'm working on Angular2 now. If I can build it out in your bootstrap, I'd be very happy to share your repo with my attendees and help publicize it.

**Comment by 0mkara** [comment]
Hi,
I apologize for not responding before your lecture. I missed this issue somehow. Looks like bugs and issues have learned to hide themselves well. I just ran this app from a fresh clone with command `meteor run --port 2100 --release 1.4.4.2 --allow-incompatible-update` and it compiled and worked great. I just has to install `@angular/cdk` as it was an addition to `@angular/material` I guess. Otherwise no problem. Let me know if you could got it working when u need it. Thanks for checking my work out :heart:

**Comment by alimgafar** [comment]
Just seeing this now - went to bulk. Thanks! I'll try it out and let you know.
